In [8]:
import os
import shutil
from tqdm import tqdm 
import geopandas as gpd

In [7]:
in_dir = "/mnt/sdd/ls789gf"

for file in tqdm(os.listdir(in_dir)):
    full_path = os.path.join(in_dir, file)
    print(os.path.exists(full_path))
    if not file.endswith("Landsat"):
        os.rename(full_path, os.path.join(in_dir, f"coords_{file}_Landsat"))

100%|██████████| 2839/2839 [00:00<00:00, 104285.48it/s]

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True

In [9]:
in_shp = '/home/rene1337/Desktop/Senegal_2002-2016_merged_cutlines_run10.gpkg'
gdf = gpd.read_file(in_shp)

In [11]:
gdf.columns

Index(['IMAGENAME', 'SENSOR', 'ACQDATE', 'CAT_ID', 'RESOLUTION', 'OFF_NADIR',
       'SUN_ELEV', 'SUN_AZ', 'SAT_ELEV', 'SAT_AZ', 'CLOUDCOVER', 'TDI',
       'DATE_DIFF', 'SCORE', 'SCAN_DIR', 'RF_MULT', 'RF_ADD', 'AOD',
       'CLOUD_FRAC', 'STATS_MIN', 'STATS_MAX', 'STATS_STD', 'STATS_MEAN',
       'STATS_PCT', 'geometry'],
      dtype='object')

In [13]:
import pandas as pd
gdf["acq_date"] = pd.to_datetime(gdf["ACQDATE"])
gdf["year"] = gdf["acq_date"].dt.year
gdf.to_file('/home/rene1337/Desktop/Senegal_2002-2016_merged_cutlines_run10_with_years.gpkg', driver='GPKG')

In [52]:
# replace id with unique_id where it exists
gdf["id"] = gdf["unique_id"].where(gdf["unique_id"].notnull(), gdf["id"])

In [54]:
gdf.to_file(in_shp.replace(".gpkg", "_with_unique_ids.gpkg"), driver="GPKG")

In [48]:
gdf_unique_ids["id"] = gdf_unique_ids["unique_id"]

/home/rene1337/miniconda3/envs/gdal/lib/python3.10/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [49]:
gdf_unique_ids

,fid,id,DeciduousLC,Dormancy_1_mean,MidGreendown_1_mean,Senescence_1_mean,Greenup_1_mean,unique_id,start_date,end_date,orig_id,part_id,layer,path,geometry,grid_id
13,53,-19_14_4_part0,NaN,NaN,NaN,NaN,NaN,-19_14_4_part0,2001-01-28,2001-06-27,13.0,0.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-16.60883 13.17529, -16.60883 13.015...",-19_14_4
14,54,-19_14_4_part1,NaN,NaN,NaN,NaN,NaN,-19_14_4_part1,2001-01-28,2001-06-27,13.0,1.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-16.46911 13.01557, -16.62883 13.015...",-19_14_4
15,57,-19_14_7_part0,NaN,NaN,NaN,NaN,NaN,-19_14_7_part0,2001-01-28,2001-06-27,14.0,0.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-16.76855 13.47473, -16.60883 13.474...",-19_14_7
16,58,-19_14_7_part1,NaN,NaN,NaN,NaN,NaN,-19_14_7_part1,2001-01-28,2001-06-27,14.0,1.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-16.46911 13.47473, -16.46911 13.315...",-19_14_7
17,59,-19_14_7_part2,NaN,NaN,NaN,NaN,NaN,-19_14_7_part2,2001-01-28,2001-06-27,14.0,2.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-16.76855 13.17529, -16.76855 13.335...",-19_14_7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,452,-16_18_3_part3,NaN,NaN,NaN,NaN,NaN,-16_18_3_part3,2000-11-11,2001-07-22,112.0,3.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-14.23333 16.46911, -14.23333 16.628...",-16_18_3
535,453,-16_18_1_part0,NaN,NaN,NaN,NaN,NaN,-16_18_1_part0,2000-11-11,2001-07-19,113.0,0.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-13.91389 16.46911, -13.91389 16.309...",-16_18_1
536,455,-16_18_1_part2,NaN,NaN,NaN,NaN,NaN,-16_18_1_part2,2000-11-11,2001-07-19,113.0,2.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-14.07361 16.16968, -14.07361 16.329...",-16_18_1
537,456,-16_18_1_part3,NaN,NaN,NaN,NaN,NaN,-16_18_1_part3,2000-11-11,2001-07-19,113.0,3.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-13.93389 16.16968, -13.93389 16.329...",-16_18_1
538,459,-16_18_2_part2,NaN,NaN,NaN,NaN,NaN,-16_18_2_part2,2000-11-11,2001-07-19,114.0,2.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-13.77417 16.16968, -13.77417 16.329...",-16_18_2

In [50]:
# merge rows where unique_id is the same
joined = gdf.join(gdf_unique_ids, on="fid", rsuffix="_right")

In [51]:
joined

,fid,id,DeciduousLC,Dormancy_1_mean,MidGreendown_1_mean,Senescence_1_mean,Greenup_1_mean,unique_id,start_date,end_date,...,Greenup_1_mean_right,unique_id_right,start_date_right,end_date_right,orig_id_right,part_id_right,layer_right,path_right,geometry_right,grid_id_right
0,3154,-19_15_1,44.974813,361.918330,321.478702,289.497048,178.787067,None,NaT,NaT,...,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,None,NaN
1,3157,-19_15_2,44.974813,361.918330,321.478702,289.497048,178.787067,None,NaT,NaT,...,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,None,NaN
2,3160,-18_15_0,3.976811,352.541547,316.534154,289.404194,172.758539,None,NaT,NaT,...,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,None,NaN
3,3163,-18_15_1,3.976811,352.541547,316.534154,289.404194,172.758539,None,NaT,NaT,...,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,None,NaN
4,3166,-18_15_2,3.976811,352.541547,316.534154,289.404194,172.758539,None,NaT,NaT,...,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,452,-16_18_3,NaN,NaN,NaN,NaN,NaN,-16_18_3_part3,2000-11-11,2001-07-22,...,NaN,-16_17_2_part0,2000-12-09,2001-07-10,88.0,0.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-13.61445 15.5708, -13.61445 15.4110...",-16_17_2
535,453,-16_18_1,NaN,NaN,NaN,NaN,NaN,-16_18_1_part0,2000-11-11,2001-07-19,...,NaN,-16_17_2_part1,2000-12-09,2001-07-10,88.0,1.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-13.47473 15.41108, -13.63445 15.411...",-16_17_2
536,455,-16_18_1,NaN,NaN,NaN,NaN,NaN,-16_18_1_part2,2000-11-11,2001-07-19,...,NaN,-16_17_2_part3,2000-12-09,2001-07-10,88.0,3.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-13.63445 15.27136, -13.63445 15.431...",-16_17_2
537,456,-16_18_1,NaN,NaN,NaN,NaN,NaN,-16_18_1_part3,2000-11-11,2001-07-19,...,NaN,-16_17_5_part0,2000-12-09,2001-07-19,89.0,0.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-13.61445 15.87024, -13.61445 15.710...",-16_17_5
538,459,-16_18_2,NaN,NaN,NaN,NaN,NaN,-16_18_2_part2,2000-11-11,2001-07-19,...,NaN,-16_17_5_part3,2000-12-09,2001-07-19,89.0,3.0,senegal_remaining_V2_filtered_split,/mnt/sdc/tree_density_and_coverage/shapefiles/...,"POLYGON ((-13.63445 15.5708, -13.63445 15.7305...",-16_17_5